version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    working_directory: ~/elixir.io/backend # setting working directory
    steps:
      - checkout
          path: ~/elixir.io #  I don't understand here
      - run:
          name: test
          command: npm run build
