version: 2.1
jobs:
  job1:
    docker:
      - image: cimg/node:18.7.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    working_directory: ~/elixir.io/backend # setting working directory
    steps:
      - checkout:
          path: ~/elixir.io # circleci should work on the subdirectories of elixir.io
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: test
          command: |
            npm install rimraf 
            npm test
      - run:
          name: build Docker image
          command: docker build -t princeigwe/elixir.io:latest .
      - run: 
          name: push Docker image
          command: |
            docker login
            docker push princeigwe/elixir.io:latest


workflows:
  elixir:
    jobs:
      - job1:
          context: 
            - DOCKER_AUTH