version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    working_directory: ~/elixir.io # setting working directory
    steps:
      - checkout
      - run:
          name: test
          command: cd backend ; npm run build
